spring:
  application:
    name: team4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://mutsa-db.cj6iy2ouw106.ap-northeast-2.rds.amazonaws.com:3306/team4_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000